/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package options;

import frame.MysqlAccess;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mxsxs2
 */
public class Config extends javax.swing.JPanel {
    private final MysqlAccess SQL = new MysqlAccess();
    private final classes.ConfigReader CR;
    /**
     * Creates new form Config
     * @param CR
     */
    public Config(classes.ConfigReader CR) {
        super.setBounds(0,0,780,577);
        initComponents();
        this.CR=CR;
        this.loadDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jNxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jChecknxtButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jNisField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jChecknisButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jWebField = new javax.swing.JTextField();
        jRootField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSaveButton = new javax.swing.JButton();
        jRespLabel = new javax.swing.JLabel();
        jLoadButton = new javax.swing.JButton();
        jResetButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(780, 577));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Next server address"));

        jNxtField.setToolTipText("Like: http:\\\\127.0.0.1:80");

        jLabel3.setText("Address:");

        jChecknxtButton.setText("Check Availability");
        jChecknxtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChecknxtButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Address with port number like: http://127.0.0.1:7876/ ");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jNxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jChecknxtButton))
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jNxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChecknxtButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jNxtField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jChecknxtButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("New Economy Movement server address (NIS)"));

        jNisField.setToolTipText("Like: http:\\\\127.0.0.1:80");

        jLabel4.setText("Address:");

        jChecknisButton.setText("Check Availability");
        jChecknisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChecknisButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Address with port number like: http://127.0.0.1:7890/ ");

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jNisField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jChecknisButton))
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jNisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChecknisButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jLayeredPane2.setLayer(jNisField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jChecknisButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Website"));

        jLabel1.setText("Address:");

        jLabel2.setText("Root Folder:");

        jWebField.setToolTipText("Like: http:\\\\127.0.0.1:80");

        jRootField.setToolTipText("Like: http:\\\\127.0.0.1:80");

        jLabel5.setText("If the address is like: http://someaddress.com/ then write the following into the field: someaddress.com");

        jLabel6.setText("If the site is in a folder on the webserver then write the folder here or leave it blank.");

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jWebField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRootField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jWebField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRootField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane3.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jWebField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jRootField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSaveButton.setText("Save changes");
        jSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveButtonActionPerformed(evt);
            }
        });

        this.jRespLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLoadButton.setText("Load from DB");
        jLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoadButtonActionPerformed(evt);
            }
        });

        jResetButton.setText("Reset");
        jResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 530, Short.MAX_VALUE)
                                .addComponent(jLayeredPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLoadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jRespLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRespLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSaveButton)
                    .addComponent(jLoadButton)
                    .addComponent(jResetButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jChecknxtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChecknxtButtonActionPerformed
        this.checkAddress("nxt");
    }//GEN-LAST:event_jChecknxtButtonActionPerformed

    private void jChecknisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChecknisButtonActionPerformed
        this.checkAddress("nem");
    }//GEN-LAST:event_jChecknisButtonActionPerformed

    private void jLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoadButtonActionPerformed
        this.loadDetails();
    }//GEN-LAST:event_jLoadButtonActionPerformed

    private void jSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveButtonActionPerformed
        this.saveDetails();
    }//GEN-LAST:event_jSaveButtonActionPerformed

    private void jResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetButtonActionPerformed
        this.resetDetails();
    }//GEN-LAST:event_jResetButtonActionPerformed
    private boolean checkAddress(String Type){
        this.jRespLabel.setText("");
        javax.swing.JTextField field=null;
        if(Type.equals("nxt")) field=this.jNxtField;
        if(Type.equals("nem")) field=this.jNisField;
        String response=this.CR.checkServer(field.getText().trim(), Type);
        field.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        if(response.equals("true")){
            field.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
            return true;
        }else if(!response.equals("false")){
            this.jRespLabel.setText(response);
        }
        return false;
    }
    private void saveDetails(){
        String web=this.jWebField.getText().trim();
        String root=this.jRootField.getText().trim();
        String nxt=this.jNxtField.getText().trim();
        String nis=this.jNisField.getText().trim();
        int abort=0;
        if(web.length()<5){
            int optionPane = javax.swing.JOptionPane.showConfirmDialog(         //Create the confirmation dialig
                    null,
                    "The web address is less than 5 characters.\n"+
                    "Do you proceed to save?",
                    "Warning",
                    javax.swing.JOptionPane.YES_NO_OPTION);
                if(optionPane==javax.swing.JOptionPane.NO_OPTION) abort++;
        }
        if(!this.checkAddress("nxt")){
             int optionPane = javax.swing.JOptionPane.showConfirmDialog(         //Create the confirmation dialig
                    null,
                    "Next address is invalid.\n"+
                    "Do you proceed to save?",
                    "Warning",
                    javax.swing.JOptionPane.YES_NO_OPTION);
                if(optionPane==javax.swing.JOptionPane.NO_OPTION) abort++;
        }
        if(!this.checkAddress("nem")){
             int optionPane = javax.swing.JOptionPane.showConfirmDialog(         //Create the confirmation dialig
                    null,
                    "Nis address is invalid.\n"+
                    "Do you proceed to save?",
                    "Warning",
                    javax.swing.JOptionPane.YES_NO_OPTION);
                if(optionPane==javax.swing.JOptionPane.NO_OPTION) abort++;
        }
        int optionPane = javax.swing.JOptionPane.showConfirmDialog(         //Create the confirmation dialig
                    null,
                    "The program will overwrite the details in the database\n"+
                    "Do you proceed to save?",
                    "Warning",
                    javax.swing.JOptionPane.YES_NO_OPTION);
                if(optionPane==javax.swing.JOptionPane.NO_OPTION) abort++;
        if(abort==0){
            Boolean update = SQL.PreparedUpdate("siteaddress", new String[]{"root_dir","web_address","nxt_address","nis_address"}, new String[]{root,web,nxt,nis}, "`id`=1", "1");
            if(update){
                this.jRespLabel.setText("Details are saved.");
            }else{
                this.jRespLabel.setText("Could not save the details.");
            }
        }
    }
    
    private void loadDetails(){
        ResultSet RS = this.SQL.PreparedSelect("siteaddress", new String[]{"root_dir","web_address","nxt_address","nis_address"}, "`id`=1", "1","");
        if(RS!=null){
            try {
                RS.first();
                this.jWebField.setText(RS.getString("web_address"));
                this.jRootField.setText(RS.getString("root_dir"));
                this.jNxtField.setText(RS.getString("nxt_address"));
                this.jNisField.setText(RS.getString("nis_address"));
            } catch (SQLException ex) {
                Logger.getLogger(Config.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void resetDetails(){
        this.jWebField.setText("");
        this.jRootField.setText("");
        this.jNxtField.setText("");
        this.jNisField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jChecknisButton;
    private javax.swing.JButton jChecknxtButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JButton jLoadButton;
    private javax.swing.JTextField jNisField;
    private javax.swing.JTextField jNxtField;
    private javax.swing.JButton jResetButton;
    private javax.swing.JLabel jRespLabel;
    private javax.swing.JTextField jRootField;
    private javax.swing.JButton jSaveButton;
    private javax.swing.JTextField jWebField;
    // End of variables declaration//GEN-END:variables
}
