/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package options;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mxsxs2
 */
public class Session extends javax.swing.JPanel {
    private final frame.MysqlAccess SQL= new frame.MysqlAccess();
    private String LastSID;
    /**
     * Creates new form Session
     */
    public Session() {
        initComponents();
        super.setBounds(0,0,870,577);
        this.selectCurrentSession();
        this.selectNextSession();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCurrentLayered = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jNS = new javax.swing.JLabel();
        jNF = new javax.swing.JLabel();
        jCP1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRespLabel = new javax.swing.JLabel();
        jNextLayered = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCS = new javax.swing.JLabel();
        jCP = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCF = new javax.swing.JTextField();
        jFinishSave = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(870, 577));
        setMinimumSize(new java.awt.Dimension(870, 577));

        jCurrentLayered.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Next Session"));
        jCurrentLayered.setMaximumSize(null);
        jCurrentLayered.setMinimumSize(null);
        jCurrentLayered.setPreferredSize(new java.awt.Dimension(550, 100));

        jLabel7.setText("Changing period:");

        jLabel8.setText("Will finish:");

        jLabel9.setText("Will started:");

        javax.swing.GroupLayout jCurrentLayeredLayout = new javax.swing.GroupLayout(jCurrentLayered);
        jCurrentLayered.setLayout(jCurrentLayeredLayout);
        jCurrentLayeredLayout.setHorizontalGroup(
            jCurrentLayeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCurrentLayeredLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jCurrentLayeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jCurrentLayeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNS, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCP1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        jCurrentLayeredLayout.setVerticalGroup(
            jCurrentLayeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCurrentLayeredLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jCurrentLayeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNS, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jCurrentLayeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNF, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jCurrentLayeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCP1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jCurrentLayered.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCurrentLayered.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCurrentLayered.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCurrentLayered.setLayer(jNS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCurrentLayered.setLayer(jNF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCurrentLayered.setLayer(jCP1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Session change period"));
        jLayeredPane1.setMaximumSize(null);
        jLayeredPane1.setMinimumSize(null);
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(550, 100));

        jLabel3.setText("Sessions will change every:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "Week", "Month", "Year" }));

        jPButton.setText("Save");
        jPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("The current session will change its original finishing date.");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        this.jRespLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jNextLayered.setBorder(javax.swing.BorderFactory.createTitledBorder("Curent Session"));
        jNextLayered.setMaximumSize(null);
        jNextLayered.setMinimumSize(null);
        jNextLayered.setPreferredSize(new java.awt.Dimension(550, 100));

        jLabel4.setText("Started:");

        jLabel5.setText("Finish:");

        jLabel6.setText("Changing period:");

        jFinishSave.setText("Save");
        jFinishSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFinishSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jNextLayeredLayout = new javax.swing.GroupLayout(jNextLayered);
        jNextLayered.setLayout(jNextLayeredLayout);
        jNextLayeredLayout.setHorizontalGroup(
            jNextLayeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNextLayeredLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jNextLayeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jNextLayeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCS, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jNextLayeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jCF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jFinishSave, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jNextLayeredLayout.setVerticalGroup(
            jNextLayeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNextLayeredLayout.createSequentialGroup()
                .addGroup(jNextLayeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFinishSave, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jNextLayeredLayout.createSequentialGroup()
                        .addGroup(jNextLayeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCS, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jNextLayeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jNextLayeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCP, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jNextLayered.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jNextLayered.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jNextLayered.setLayer(jCS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jNextLayered.setLayer(jCP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jNextLayered.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jNextLayered.setLayer(jCF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jNextLayered.setLayer(jFinishSave, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRespLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNextLayered, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCurrentLayered, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRespLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNextLayered, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCurrentLayered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPButtonActionPerformed
        this.setPeriod();
    }//GEN-LAST:event_jPButtonActionPerformed

    private void jFinishSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFinishSaveActionPerformed
        this.saveFinishDate();
    }//GEN-LAST:event_jFinishSaveActionPerformed
    private void saveFinishDate(){
        boolean answ=this.SQL.PreparedUpdate("session", new String[]{"end"}, new String[]{this.jCF.getText()}, "`SID`="+this.LastSID, "1");
        if(answ!=false){
            this.jRespLabel.setText("End date changed.");
            this.selectCurrentSession();
            this.selectNextSession();
        }else{
            this.jRespLabel.setText("Could not change the end date.");
        }
    }
    private void selectCurrentSession(){
        try {
            java.sql.ResultSet RS=SQL.PreparedSelect("session", new String[]{"SID","start","end","changeperiod"}, "", "1", "SID DESC");
            if(RS.first()){
                RS.beforeFirst();
                while(RS.next()){
                    this.LastSID=RS.getString("SID");
                    this.jCS.setText(RS.getString("start"));
                    this.jCF.setText(RS.getString("end"));
                    this.jCP.setText(RS.getString("changeperiod"));
                    this.jComboBox1.setSelectedItem(RS.getString("changeperiod"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Session.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void selectNextSession(){
        try {
            String Period=this.jCP.getText().toUpperCase();
            String state="SELECT `end`,DATE_ADD(`end`, INTERVAL 1 "+Period+") as `start`,`changeperiod` FROM `session` ORDER BY SID DESC LIMIT 1";
            java.sql.PreparedStatement Statement=this.SQL.Connect.prepareStatement(state);
            java.sql.ResultSet RS=Statement.executeQuery();
            if(RS.first()){
                RS.beforeFirst();
                while(RS.next()){
                    this.jNS.setText(RS.getString("start"));
                    this.jNF.setText(RS.getString("end"));
                    this.jCP1.setText(RS.getString("changeperiod"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Session.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void setPeriod(){
        try {
            String state="UPDATE `session` SET `changeperiod`='"+this.jComboBox1.getSelectedItem().toString()+"' WHERE `SID`="+this.LastSID;
            java.sql.PreparedStatement Statement=this.SQL.Connect.prepareStatement(state);
            int Res = Statement.executeUpdate();
            if(Res>0){
                this.jRespLabel.setText("The period is changed");
                this.selectCurrentSession();
                this.selectNextSession();
            }else{
                this.jRespLabel.setText("Could not change the period");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Session.class.getName()).log(Level.SEVERE, null, ex);
            this.jRespLabel.setText("Could not change the period");
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jCF;
    private javax.swing.JLabel jCP;
    private javax.swing.JLabel jCP1;
    private javax.swing.JLabel jCS;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLayeredPane jCurrentLayered;
    private javax.swing.JButton jFinishSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel jNF;
    private javax.swing.JLabel jNS;
    private javax.swing.JLayeredPane jNextLayered;
    private javax.swing.JButton jPButton;
    private javax.swing.JLabel jRespLabel;
    // End of variables declaration//GEN-END:variables
}
