/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;

/**
 *
 * @author Mxsxs2
 */
public class LoginFrame extends javax.swing.JFrame {
    private final classes.ConfigReader cr=new classes.ConfigReader();
    private String Eligibility;
    private String UserID;
    private String UserName;
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        super.setLocationRelativeTo(null);
        this.setLogo();
        this.SWThread();
        this.setBounds(0,0,302,340);
        super.setLocationRelativeTo(null);
        this.setKeyListeners();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLoginLayer = new javax.swing.JLayeredPane();
        jBack = new javax.swing.JLabel();
        jPass = new javax.swing.JPasswordField();
        jName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLoginButton = new javax.swing.JButton();
        jCRResp = new javax.swing.JLabel();
        jLoadLayer = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logofull.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        this.jBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Password");

        jLabel1.setText("Username");

        jLoginButton.setText("Login");
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });

        this.jCRResp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jCRResp.setToolTipText("If there is an error. Som functions wont work.");

        javax.swing.GroupLayout jLoginLayerLayout = new javax.swing.GroupLayout(jLoginLayer);
        jLoginLayer.setLayout(jLoginLayerLayout);
        jLoginLayerLayout.setHorizontalGroup(
            jLoginLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginLayerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLoginLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCRResp, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBack, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jLoginLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLoginLayerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jLoginLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLoginButton)
                        .addGroup(jLoginLayerLayout.createSequentialGroup()
                            .addGroup(jLoginLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginLayerLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18))
                                .addGroup(jLoginLayerLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(16, 16, 16)))
                            .addGroup(jLoginLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jName)
                                .addComponent(jPass, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jLoginLayerLayout.setVerticalGroup(
            jLoginLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginLayerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBack, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jCRResp, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLoginLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLoginLayerLayout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addGroup(jLoginLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jLoginLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLoginButton)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        jLoginLayer.setLayer(jBack, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLoginLayer.setLayer(jPass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLoginLayer.setLayer(jName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLoginLayer.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLoginLayer.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLoginLayer.setLayer(jLoginButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLoginLayer.setLayer(jCRResp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("Loading. Please wait.");

        javax.swing.GroupLayout jLoadLayerLayout = new javax.swing.GroupLayout(jLoadLayer);
        jLoadLayer.setLayout(jLoadLayerLayout);
        jLoadLayerLayout.setHorizontalGroup(
            jLoadLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
            .addGroup(jLoadLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLoadLayerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLoadLayerLayout.setVerticalGroup(
            jLoadLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jLoadLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLoadLayerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLoadLayer.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLoginLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 102, Short.MAX_VALUE)
                    .addComponent(jLoadLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 102, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLoginLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 87, Short.MAX_VALUE)
                    .addComponent(jLoadLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 87, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        this.Login();
    }//GEN-LAST:event_jLoginButtonActionPerformed
    private void setLogo(){
        javax.swing.ImageIcon pic=new javax.swing.ImageIcon(getClass().getResource("/img/logofull.png"));
        //int imageW = pic.getIconWidth();
        //int imageH = pic.getIconHeight();
        //java.awt.image.BufferedImage bi = new java.awt.image.BufferedImage(imageW, imageH, java.awt.image.BufferedImage.TYPE_INT_ARGB);
        //java.awt.Graphics g = bi.createGraphics();
        //g.drawImage(pic.getImage(), 286, 124, imageW, imageH, null, null);
        jLabel4.setIcon(new javax.swing.ImageIcon(pic.getImage().getScaledInstance(286, 124,  java.awt.Image.SCALE_SMOOTH)));
    }
    private void SWThread(){
        this.jLoginLayer.setVisible(false);
        this.jLoadLayer.setVisible(true);
        javax.swing.SwingWorker<Void, Void> SW = new javax.swing.SwingWorker<Void, Void>(){
         @Override
         protected Void doInBackground() throws Exception {
            if(!cr.readConfigFile()){
                        jCRResp.setText("Config reader: "+cr.getError());
                        jCRResp.setForeground(java.awt.Color.RED);
                        //jLoginButton.setEnabled(false);
                    }else{
                        jCRResp.setText("Config reader: OK");
                        jCRResp.setForeground(java.awt.Color.GREEN);
                    }
            
            //for(String s:cr.getValues()){
                //System.out.println(s);
            //}
            return null;
         }
      };
      SW.addPropertyChangeListener((java.beans.PropertyChangeEvent evt) -> {
          if (evt.getPropertyName().equals("state")) {
              if (evt.getNewValue() == javax.swing.SwingWorker.StateValue.DONE) {
                  
                  jLoginLayer.setVisible(true);
                  jLoadLayer.setVisible(false);
              }
          }
        });
      SW.execute();
    }
    private void Login(){
        String UName = this.jName.getText();
        String Pass = new String(this.jPass.getPassword());
        if(UName.equals("") || Pass.equals("")){
            this.jBack.setText("Fill the fields.");
        }else{
            MysqlAccess SQL = new MysqlAccess();
            try {
                PreparedStatement statement = SQL.Connect.prepareStatement("SELECT `id`, `auth`"
                        + "FROM `user`"
                        + "WHERE `name`=? AND `pass`=?"    
                        + "LIMIT 1");
                statement.setString(1, UName);
                statement.setString(2, Pass);
                ResultSet RS = statement.executeQuery();
                if(RS.first()){
                        this.Eligibility=RS.getString("auth");
                        this.UserName=UName;
                        this.UserID=RS.getString("id");
                        MainFrame main= new MainFrame();
                                  main.passCR(this.cr);
                                  main.setUser(UName, RS.getString("id"), RS.getString("auth"));
                                  main.setVisible(true);
                        //this.dispatchEvent(new java.awt.event.WindowEvent(this, java.awt.event.WindowEvent.WINDOW_CLOSING));
                        java.util.Date date= new java.util.Date();
                        SQL.PreparedUpdate("user", new String[]{"lastlogin"}, new String[]{new Timestamp(date.getTime()).toString()}, "`id`='"+this.UserID+"'", "1");
                        this.dispose();
                    
                }else{
                    this.jBack.setText("Wrong password or username.");
                }
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        
    }
    public String[] getLoginedDetails(){
        if(this.Eligibility!=null && this.UserID!=null && this.UserName!=null){
            String[] Details={this.Eligibility,
                              this.UserID,
                              this.UserName};
            return Details;                    
        }
        return null;
    }
    private void setKeyListeners(){
        java.awt.event.KeyAdapter Keylistener = new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt){
                if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
                    Login();
                }
            }
        };
        this.jPass.addKeyListener(Keylistener);
        this.jName.addKeyListener(Keylistener);
        this.jLoginButton.addKeyListener(Keylistener);
    }
    
    
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
             javax.swing.UIManager.put("nimbusBase",new Color(65,206,123));
            javax.swing.UIManager.put("control", new Color(255,255,255));
            javax.swing.UIManager.put("nimbusBlueGrey", new Color(65,206,123));
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBack;
    private javax.swing.JLabel jCRResp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLoadLayer;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JLayeredPane jLoginLayer;
    private javax.swing.JTextField jName;
    private javax.swing.JPasswordField jPass;
    // End of variables declaration//GEN-END:variables
}
