/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

/**
 *
 * @author Mxsxs2
 */
public class MainFrame extends javax.swing.JFrame {
    protected String[] User= new String[3];
    private classes.ConfigReader cr;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        super.setBounds(0, 0, 795, 670);
        //this.chkConfig();
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelContainer = new javax.swing.JLayeredPane();
        jWelcomeLabel = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jConfigLabel = new javax.swing.JLabel();
        jCResLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuReport = new javax.swing.JMenu();
        jMenuSiteTExts = new javax.swing.JMenu();
        jMenuSession = new javax.swing.JMenu();
        jRefundMenu = new javax.swing.JMenu();
        jAddressMenu = new javax.swing.JMenu();
        jCollectMenu = new javax.swing.JMenu();
        jConfigMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        jButton1.setText("Ok");

        jLabel1.setText("The configuration file set incorectly. Some functions might not work.");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelContainer.setMinimumSize(new java.awt.Dimension(870, 577));

        jWelcomeLabel.setText("Welcome");

        javax.swing.GroupLayout jPanelContainerLayout = new javax.swing.GroupLayout(jPanelContainer);
        jPanelContainer.setLayout(jPanelContainerLayout);
        jPanelContainerLayout.setHorizontalGroup(
            jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addComponent(jWelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContainerLayout.setVerticalGroup(
            jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addComponent(jWelcomeLabel)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanelContainer.setLayer(jWelcomeLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane1.setBackground(new java.awt.Color(255, 51, 51));
        jLayeredPane1.setMaximumSize(new java.awt.Dimension(780, 30));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(780, 30));

        jConfigLabel.setText("Configuration file status:");

        jCResLabel.setForeground(new java.awt.Color(255, 51, 51));
        jCResLabel.setText("OK");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jConfigLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCResLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConfigLabel)
                    .addComponent(jCResLabel))
                .addGap(3, 3, 3))
        );
        jLayeredPane1.setLayer(jConfigLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jCResLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuReport.setText("Reports");
        jMenuReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuReportMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuReport);

        jMenuSiteTExts.setText("Site Texts");
        jMenuSiteTExts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSiteTExtsMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSiteTExts);

        jMenuSession.setText("Session");
        jMenuSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSessionMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSession);

        jRefundMenu.setText("NXT Refund");
        jRefundMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRefundMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(jRefundMenu);

        jAddressMenu.setText("Addresses");
        jAddressMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAddressMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(jAddressMenu);

        jCollectMenu.setText("Collect");
        jCollectMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCollectMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(jCollectMenu);

        jConfigMenu.setText("Config");
        jConfigMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jConfigMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(jConfigMenu);

        jMenu1.setText("Log out");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 795, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSiteTExtsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSiteTExtsMouseClicked
        options.SiteTexts ST= new options.SiteTexts();
                this.jPanelContainer.setVisible(false);      
                this.jPanelContainer.removeAll();
                this.jPanelContainer.add(ST);
                this.jPanelContainer.setVisible(true);
    }//GEN-LAST:event_jMenuSiteTExtsMouseClicked

    private void jMenuSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSessionMouseClicked
        options.Session S= new options.Session();
                this.jPanelContainer.setVisible(false);      
                this.jPanelContainer.removeAll();
                this.jPanelContainer.add(S);
                this.jPanelContainer.setVisible(true);
    }//GEN-LAST:event_jMenuSessionMouseClicked

    private void jMenuReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuReportMouseClicked
        options.EntryReport nxte= new options.EntryReport(cr);
                this.jPanelContainer.setVisible(false);      
                this.jPanelContainer.removeAll();
                this.jPanelContainer.add(nxte);
                this.jPanelContainer.setVisible(true);
    }//GEN-LAST:event_jMenuReportMouseClicked

    private void jRefundMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRefundMenuMouseClicked
        options.Refund refund= new options.Refund(cr);
                this.jPanelContainer.setVisible(false);      
                this.jPanelContainer.removeAll();
                this.jPanelContainer.add(refund);
                this.jPanelContainer.setVisible(true);
    }//GEN-LAST:event_jRefundMenuMouseClicked

    private void jAddressMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddressMenuMouseClicked
        options.Addresses add= new options.Addresses(cr.getValues());
                this.jPanelContainer.setVisible(false);      
                this.jPanelContainer.removeAll();
                this.jPanelContainer.add(add);
                this.jPanelContainer.setVisible(true);
    }//GEN-LAST:event_jAddressMenuMouseClicked

    private void jConfigMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jConfigMenuMouseClicked
        options.Config config= new options.Config(cr);
                this.jPanelContainer.setVisible(false);      
                this.jPanelContainer.removeAll();
                this.jPanelContainer.add(config);
                this.jPanelContainer.setVisible(true);
    }//GEN-LAST:event_jConfigMenuMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        this.User[0]=this.User[1]=this.User[2]=null;
        LoginFrame LF=new LoginFrame();
                   LF.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jCollectMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCollectMenuMouseClicked
        options.Collect add= new options.Collect(this.cr.getValues());
                this.jPanelContainer.setVisible(false);      
                this.jPanelContainer.removeAll();
                this.jPanelContainer.add(add);
                this.jPanelContainer.setVisible(true);
    }//GEN-LAST:event_jCollectMenuMouseClicked
    public void setUser(String Name, String ID, String Auth){
        this.User[0]=ID;
        this.User[1]=Name;
        this.User[2]=Auth;
        this.jWelcomeLabel.setText("Welcome "+User[1]+"! Select one of the menus to start operating on the website.");
        this.jWelcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    }
    public void passCR(classes.ConfigReader CR){
        this.cr=CR;
    }
    private void chkConfig(){
        Thread queryThread = new Thread() {
            @SuppressWarnings("empty-statement")
            @Override
            public void run() {
                    if(!cr.readConfigFile()){
                        jCResLabel.setText("Error. Some functions will not work!");
                    }else{
                        jCResLabel.setText("ok");
                        jCResLabel.setForeground(java.awt.Color.GREEN);
                    };
            }
        };
        queryThread.start();
            
            
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jAddressMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jCResLabel;
    private javax.swing.JMenu jCollectMenu;
    private javax.swing.JLabel jConfigLabel;
    private javax.swing.JMenu jConfigMenu;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuReport;
    private javax.swing.JMenu jMenuSession;
    private javax.swing.JMenu jMenuSiteTExts;
    private javax.swing.JLayeredPane jPanelContainer;
    private javax.swing.JMenu jRefundMenu;
    private javax.swing.JLabel jWelcomeLabel;
    // End of variables declaration//GEN-END:variables
}
